### ISSUE TITLE
Tags not showing up on Main page

### ISSUE THREAD

**Issue by twin0mega** [Propheus/SG-Game-Tags#1]
I've been using this script now for a week and the tags do not show up on the main pages. They do however show up when you click on the game and you go to its individual page.

Can you please fix this? Thanks

![01](https://cloud.githubusercontent.com/assets/15787068/16387128/2783a618-3c59-11e6-9afc-e414e482be4a.jpg)
![02](https://cloud.githubusercontent.com/assets/15787068/16387129/2787fc5e-3c59-11e6-84bc-0c52110d5384.jpg)

**Comment by christhofer** [comment]
Weird... It works fine in my Firefox and Chrome.

What is your browser?
Are you only using wishlist tag? Wishlist and Hidden tags only appear inside giveaway page.

Try press F12 and go to console tab to see if there are any errors.

EDIT: Oops I pressed wrong button to submit this comment
